version: '3'

services:
    app:
        build: .
        container_name: bank-api-cter-app
        volumes:
            - .:/var/www
            - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        depends_on:
            - db
        networks:
          - cter-network
        extra_hosts:
          - "host.docker.internal:172.17.0.1"

    nginx:
        build: .docker/nginx
        container_name: bank-api-cter-nginx
        restart: always
        tty: true
        ports:
            - "8002:80"
        volumes:
            - .:/var/www
        depends_on:
            - app
        networks:
          - cter-network
        extra_hosts:
          - "host.docker.internal:172.17.0.1"

    db:
        build: ./.docker/mysql
        container_name: bank-api-cter-db
        restart: always
        tty: true
        ports:
            - "33008:3306"
        volumes:
            - ./.docker/dbdatacter:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=bank_api
            - MYSQL_ROOT_PASSWORD=root
        networks:
          - cter-network

networks:
  cter-network:
    driver: bridge
