version: '3'

services:
    app:
        build: .
        container_name: bank-api-bbx-app
        volumes:
            - .:/var/www
            - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        depends_on:
            - db
#        networks:
#          - bbx-network
#        extra_hosts:
#          - "host.docker.internal:172.17.0.1"

    nginx:
        build: .docker/nginx
        container_name: bank-api-bbx-nginx
        restart: always
        tty: true
        ports:
            - "8001:80"
        volumes:
            - .:/var/www
        depends_on:
            - app
#        networks:
#          - bbx-network
#        extra_hosts:
#          - "host.docker.internal:172.17.0.1"

    db:
        build: ./.docker/mysql
        container_name: bank-api-bbx-db
        restart: always
        tty: true
        ports:
            - "33007:3306"
        volumes:
            - ./.docker/dbdatabbx:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=bank_api
            - MYSQL_ROOT_PASSWORD=root
#        networks:
#          - bbx-network

    consumer:
      build: .
      container_name: bank-api-bbx-consumer
      volumes:
        - .:/var/www
        - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      depends_on:
        - db
      working_dir: /var/www
      entrypoint: [ 'php', '/var/www/artisan', 'kafka:consumer' ]
#
#networks:
#  bbx-network:
#    driver: bridge
